import {
  BusinessSettings,
  QuoteRequest,
  ReviewItem,
  ServiceItem,
  GalleryItem,
  BeforeAfterItem,
  FaqItem,
} from '@/types';

export const INITIAL_SETTINGS: BusinessSettings = {
  businessName: 'Ngongotaha Panel & Paint',
  ownerPlaceholder: '[Darren - Shop Owner]',
  phone: '+64 27 684 1468',
  whatsapp: '+64 27 684 1468',
  emailPlaceholder: '[contact@ngongotahapanelpaint.co.nz]',
  address: '142 Oturoa Road, Ngongotahā, Rotorua 3072, New Zealand',
  googleRating: 4.4,
  reviewCount: 7,
  googleReviewsUrl: 'https://maps.google.com/?q=Ngongotaha+Panel+%26+Paint+142+Oturoa+Road+Rotorua',
  googleMapsUrl: 'https://maps.google.com/?q=Ngongotaha+Panel+%26+Paint+142+Oturoa+Road+Ngongotah%C4%81+Rotorua+3072+New+Zealand',
  googleMapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3163.5786480537446!2d176.1953935!3d-38.0827282!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6d6e7db3e33b666d%3A0x6a05e54d89a29d9e!2s142%20Oturoa%20Rd%2C%20Ngongotah%C4%81%2C%20Rotorua%203072%2C%20New%20Zealand!5e0!3m2!1sen!2snz!4v1710000000000!5m2!1sen!2snz',
  heroHeadline: 'Flawless Panel & Paint in Rotorua',
  heroSubheadline: 'From high-gloss spray finishes and chassis rust repairs to urgent bumper fixes. Same-day & next-day turnaround backed by 4.4 stars on Google.',
  trustTurnaround: 'Same-Day / Next-Day',
  trustPricing: 'Honest & Fair Pricing',
  trustWorkmanship: 'Master Workmanship',
  announcement: {
    isEnabled: true,
    badge: 'Open for Inquiries',
    text: 'Need an urgent bumper fix or WoF rust repair? Call or WhatsApp Darren directly today.',
    linkUrl: '#quote',
    linkText: 'Get Free Quote',
  },
  openingHours: {
    monday: { isOpen: true, openTime: '08:00', closeTime: '17:00', note: '[Placeholder Hours - Editable]' },
    tuesday: { isOpen: true, openTime: '08:00', closeTime: '17:00', note: '[Placeholder Hours - Editable]' },
    wednesday: { isOpen: true, openTime: '08:00', closeTime: '17:00', note: '[Placeholder Hours - Editable]' },
    thursday: { isOpen: true, openTime: '08:00', closeTime: '17:00', note: '[Placeholder Hours - Editable]' },
    friday: { isOpen: true, openTime: '08:00', closeTime: '16:30', note: '[Placeholder Hours - Editable]' },
    saturday: { isOpen: false, openTime: '08:30', closeTime: '12:00', note: '[Appointment Only - Placeholder]' },
    sunday: { isOpen: false, openTime: '00:00', closeTime: '00:00', note: '[Closed Sundays]' },
  },
  holidayNotice: 'Holiday hours may vary. Please call ahead on +64 27 684 1468 to confirm workshop availability.',
  appearance: {
    accentColor: '#FF3B30',
    theme: 'dark',
  },
  seo: {
    metaTitle: 'Ngongotaha Panel & Paint | Rotorua Panel Beater & Spray Painting',
    metaDescription: 'Expert panel beating, spray painting, chassis rust repair, and bumper fixes in Ngongotahā, Rotorua. 4.4 Google rating. Fair pricing & fast turnaround.',
    keywords: ['panel beater Rotorua', 'auto paint Rotorua', 'rust repair Ngongotaha', 'dent repair Rotorua', 'bumper repair Rotorua', 'WoF rust repair'],
    ogImage: '/images/ute-paint-booth.png',
  },
};

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'srv-1',
    title: 'Panel Beating & Chassis Repair',
    slug: 'panel-beating',
    shortDescription: 'Precision structural alignment, panel beating, and chassis restoration for accident damage and structural integrity.',
    fullDescription: 'Using hydraulic alignment rigs and seasoned metal-shaping techniques, we restore damaged body panels, quarter panels, and structural chassis back to factory specifications. Known across Rotorua for honest assessments and non-inflated repairs.',
    turnaroundTime: 'Often Same-Day or 1-3 Days',
    iconName: 'Hammer',
    imageUrl: '/images/ute-paint-booth.png',
    keyBenefits: ['Precision chassis rust and structural alignment', 'Warrant of Fitness (WoF) compliance certification', 'Preserves original metal wherever possible'],
    isFeatured: true,
    order: 1,
  },
  {
    id: 'srv-2',
    title: 'Spray Painting & Gloss Finishes',
    slug: 'spray-painting',
    shortDescription: 'Computerised colour matching, premium oven baking, and deep mirror-gloss clearcoats that endure the NZ sun.',
    fullDescription: 'Our spray booth delivers factory-grade finishes from single-panel blend-ins to complete resprays. We utilise premium automotive enamels and dual-action clearcoats formulated to resist UV fading and environmental wear.',
    turnaroundTime: '1 - 2 Days',
    iconName: 'Paintbrush',
    imageUrl: '/images/ute-paint-booth.png',
    keyBenefits: ['Exact computerized tint and metallic flake match', 'High-solid glossy clearcoat for long-term UV protection', 'Bake-cured finish for scratch resistance'],
    isFeatured: true,
    order: 2,
  },
  {
    id: 'srv-3',
    title: 'Rust Repair & WoF Compliance',
    slug: 'rust-repair',
    shortDescription: 'Specialised cut-out, steel plating, and seam sealing to pass strict NZTA Warrant of Fitness inspections.',
    fullDescription: 'Chassis and sill rust will fail your WoF instantly. We cut out cancer rust completely down to clean bare metal, fabricate fresh heavy-gauge replacement steel, weld, zinc-prime, and rust-proof the cavity so your vehicle passes inspection with flying colours.',
    turnaroundTime: 'Fast Turnaround (No long shop holds)',
    iconName: 'ShieldAlert',
    imageUrl: '/images/ute-paint-booth.png',
    keyBenefits: ['100% WoF compliant metal fabrication', 'Anti-corrosive epoxy sealing & cavity wax protection', 'Verified by local guides: "didn\'t hold onto the car for days"'],
    isFeatured: true,
    order: 3,
  },
  {
    id: 'srv-4',
    title: 'Dent & Ding Repair',
    slug: 'dent-repair',
    shortDescription: 'From carpark shopping trolley dings to crease damage, restored smoothly without unnecessary panel replacements.',
    fullDescription: 'Minor dents compromise the visual line of your car. We employ specialized pullers, fine picks, and micro-filling techniques to eliminate door dings, crease impacts, and road debris dents with minimal turnaround time.',
    turnaroundTime: 'Same-Day Service Available',
    iconName: 'Sparkles',
    imageUrl: '/images/interior-detail.png',
    keyBenefits: ['Fast turnarounds - back on the road in hours', 'Affordable rates that save on insurance excess', 'Smooth factory contour restoration'],
    isFeatured: true,
    order: 4,
  },
  {
    id: 'srv-5',
    title: 'Bumper Repair & Emergency Fixes',
    slug: 'bumper-repair',
    shortDescription: 'Plastic welding, clip re-securing, scuff resprays, and mobile emergency temporary fixes to keep you mobile.',
    fullDescription: 'Is your bumper hanging off after a curb impact or carpark scrape? We perform heavy-duty plastic welding, tab re-anchoring, and emergency temporary fixes to get you driving safely right away, followed by seamless paint blending.',
    turnaroundTime: 'Emergency Same-Day / While-You-Wait',
    iconName: 'Wrench',
    imageUrl: '/images/interior-detail.png',
    keyBenefits: ['Emergency callouts and rapid temporary re-securing', 'High-strength plastic fusion welding', 'Saves hundreds compared to buying OEM replacement bumpers'],
    isFeatured: true,
    order: 5,
  },
];

export const INITIAL_REVIEWS: ReviewItem[] = [
  {
    id: 'rev-1',
    authorName: 'Alison W.',
    isLocalGuide: true,
    rating: 5,
    text: "I have used them twice. Once for chassis rust and once for a ding.. The guy that did it was excellent. Very happy with the job and he didn't hold onto the car for days.",
    source: 'Google Reviews',
    isVisible: true,
    order: 1,
  },
  {
    id: 'rev-2',
    authorName: 'Zachariah J.',
    isLocalGuide: false,
    rating: 5,
    text: "Contacted him and had the car in the next day and done before the end of the day. 10/10 would definitely recommend does an incredible job and fairly priced too.",
    source: 'Google Reviews',
    isVisible: true,
    order: 2,
  },
  {
    id: 'rev-3',
    authorName: 'Janice G.',
    isLocalGuide: true,
    rating: 5,
    text: "I called Darren to do a temporary fix on my front bumper which was hanging off and I couldn't drive it. He came to my house and fixed it so that I can drive it and didn't charge me. What a legend!",
    source: 'Google Reviews',
    isVisible: true,
    order: 3,
  },
  {
    id: 'rev-4',
    authorName: 'Tracy J.',
    isLocalGuide: false,
    rating: 5,
    text: "Absolutely outstanding service and workmanship. Would highly recommend.",
    source: 'Google Reviews',
    isVisible: true,
    order: 4,
  },
  {
    id: 'rev-5',
    authorName: 'Jane W.',
    isLocalGuide: false,
    rating: 5,
    text: "I am so thankful for the job done on my car much appreciated a very kind, thorough man",
    source: 'Google Reviews',
    isVisible: true,
    order: 5,
  },
];

export const INITIAL_GALLERY: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Classic Ute Full Body Respray in Booth',
    category: 'Paint Work',
    imageUrl: '/images/ute-paint-booth.png',
    caption: 'Real Workshop Photo: Masked and freshly clearcoated black ute inside our Ngongotaha spray booth with mirror gloss finish.',
    isRealWork: true,
    order: 1,
  },
  {
    id: 'gal-2',
    title: 'Interior Panel Alignment & Carbon Sport Trim',
    category: 'Bumpers & Detailing',
    imageUrl: '/images/interior-detail.png',
    caption: 'Real Workshop Photo: Sport interior door card alignment, switchgear reassembly, and custom trim detailing.',
    isRealWork: true,
    order: 2,
  },
  {
    id: 'gal-3',
    title: 'Chassis Rail & Sill Rust Cut-Out & WoF Plate',
    category: 'Rust & WoF',
    imageUrl: '/images/ute-paint-booth.png',
    caption: 'Heavy rust excised from chassis rail, replaced with welded steel plate, sealed with epoxy primer for NZTA WoF pass.',
    isRealWork: false,
    order: 3,
  },
  {
    id: 'gal-4',
    title: 'Front Quarter Panel Impact Beating & Blend',
    category: 'Panel & Dents',
    imageUrl: '/images/ute-paint-booth.png',
    caption: 'Accident crease pulled and hammer-finished, followed by feather edging and 2-stage metallic clearcoat.',
    isRealWork: false,
    order: 4,
  },
  {
    id: 'gal-5',
    title: 'Front Bumper Tab Re-weld & Gloss Finish',
    category: 'Bumpers & Detailing',
    imageUrl: '/images/interior-detail.png',
    caption: 'Repaired fractured mounting tabs and repainted scuffed chin spoiler to OEM spec.',
    isRealWork: false,
    order: 5,
  },
];

export const INITIAL_BEFORE_AFTER: BeforeAfterItem[] = [
  {
    id: 'ba-1',
    title: 'Ute Bed & Quarter Panel Restoration',
    vehicle: 'Holden / Chevy Classic Utility',
    description: 'Preparation masking vs final mirror clearcoat finish inside the Ngongotahā spray booth.',
    beforeImageUrl: '/images/ute-paint-booth.png',
    afterImageUrl: '/images/ute-paint-booth.png',
    beforeLabel: 'Masking & Prep Stage',
    afterLabel: 'Fresh Gloss Clearcoat',
    order: 1,
  },
  {
    id: 'ba-2',
    title: 'Chassis Rust Cut & Structural WoF Patch',
    vehicle: 'Toyota Hilux 4WD',
    description: 'Heavy corroded sill section cut back to healthy steel, welded with fresh steel, primed and anti-stone chip coated.',
    beforeImageUrl: '/images/ute-paint-booth.png',
    afterImageUrl: '/images/ute-paint-booth.png',
    beforeLabel: 'Corroded WoF Failure',
    afterLabel: 'Welded & Certified Finish',
    order: 2,
  },
];

export const INITIAL_FAQS: FaqItem[] = [
  {
    id: 'faq-1',
    question: 'How quickly can you repair my vehicle?',
    answer: 'Turnaround time depends on the job size, but as our verified customers note, we often complete jobs same-day or next-day! We take pride in never holding onto your car for unnecessary days.',
    category: 'Turnaround & Scheduling',
    order: 1,
  },
  {
    id: 'faq-2',
    question: 'Can you help with WoF rust repairs?',
    answer: 'Yes! Chassis rust and structural sill corrosion are our specialties. We cut away the rusted sections completely, weld in certified structural steel, seal with corrosion inhibitors, and ensure your vehicle is ready to pass its Warrant of Fitness.',
    category: 'Rust & WoF',
    order: 2,
  },
  {
    id: 'faq-3',
    question: 'Do you work with insurance claims or private repairs?',
    answer: 'We cater to both private repairs and insurance claims. Because we keep overheads reasonable, private customers often save substantially compared to franchise collision centres.',
    category: 'Insurance & Pricing',
    order: 3,
  },
  {
    id: 'faq-4',
    question: 'Can you give me a quote from photos?',
    answer: 'Absolutely. Use our online quote request form or send us photos directly over WhatsApp (+64 27 684 1468). Include close-up shots of the damage and a wider angle of the vehicle for an accurate estimate.',
    category: 'Quotes',
    order: 4,
  },
  {
    id: 'faq-5',
    question: 'Where are you located in Rotorua?',
    answer: 'We are conveniently located at 142 Oturoa Road, Ngongotahā, Rotorua 3072. There is easy vehicle access and parking right outside the workshop.',
    category: 'Location',
    order: 5,
  },
];

export const INITIAL_QUOTES: QuoteRequest[] = [
  {
    id: 'qt-101',
    name: 'Sarah Henderson',
    phone: '+64 21 892 4110',
    email: 'sarah.h@gmail.com',
    vehicleMake: 'Mazda',
    vehicleModel: 'CX-5',
    vehicleYear: '2019',
    serviceType: 'Bumper Repair & Emergency Fixes',
    description: 'Reversed into a low post in carpark. Rear bumper cracked on driver side and clips came loose.',
    photoUrls: ['/images/ute-paint-booth.png'],
    status: 'new',
    notes: 'Urgent for weekend trip to Taupo.',
    createdAt: '2026-09-30T10:15:00Z',
    updatedAt: '2026-09-30T10:15:00Z',
  },
  {
    id: 'qt-102',
    name: 'David McLean',
    phone: '+64 27 334 9821',
    email: 'david.mclean@xtra.co.nz',
    vehicleMake: 'Nissan',
    vehicleModel: 'Navara D40',
    vehicleYear: '2012',
    serviceType: 'Rust Repair & WoF Compliance',
    description: 'Failed WoF yesterday at VTNZ due to rust on right rear chassis rail and passenger door sill.',
    photoUrls: ['/images/ute-paint-booth.png'],
    status: 'contacted',
    notes: 'Called customer, asked him to drop by Thursday 9am for quick steel measure up.',
    createdAt: '2026-09-29T14:40:00Z',
    updatedAt: '2026-09-29T16:00:00Z',
  },
];
